spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/first?useUnicode=true&characterEncoding=utf-8&&useSSL=true
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#  server:
#    context-path:  /product
server:
  servlet:
    context-path:  /product
